export const TTL_MAIL_RESEND_IN_SECOND = 300;
export const TTL_MAIL_RESET_PASSWORD_RESEND_IN_SECOND = 60;
export const TTL_MAIL_RESET_INVITED_RESEND_IN_SECOND = 60;
export const TTL_MAIL_INVITED_RESEND_IN_SECOND = 60;
export const TTL_CODE_VERIFY_PASSWORD_IN_SECOND = 180;
